# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ChatService.proto for package 'simplechat'

require 'grpc'
require 'ChatService'

module Simplechat
  module ChatService

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'simplechat.ChatService'

      rpc :SendMessage, Message, MessageResponse
      rpc :GetChannelMessages, Channel, stream(UserMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
