# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatService.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "simplechat.Channel" do
    optional :name, :string, 1
  end
  add_message "simplechat.Message" do
    optional :action, :string, 1
    optional :content, :string, 2
    optional :channel, :string, 3
  end
  add_message "simplechat.MessageResponse" do
    optional :status, :uint32, 1
    optional :message, :string, 2
  end
  add_message "simplechat.UserMessage" do
    optional :timestamp, :string, 1
    optional :nickname, :string, 2
    optional :message, :string, 3
  end
end

module Simplechat
  Channel = Google::Protobuf::DescriptorPool.generated_pool.lookup("simplechat.Channel").msgclass
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("simplechat.Message").msgclass
  MessageResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("simplechat.MessageResponse").msgclass
  UserMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("simplechat.UserMessage").msgclass
end
