# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ChatService.proto for package 'proto'

require 'grpc'
require 'ChatService'

module Proto
  module SimpleChat

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.SimpleChat'

      rpc :Authorize, RequestAuthorize, ResponseAuthorize
      rpc :Connect, RequestConnect, stream(Event)
      rpc :SendCommand, Command, None
    end

    Stub = Service.rpc_stub_class
  end
end
